import localFont from "next/font/local";
import "./globals.css";
import Header from "@/componets/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Pokeman App",
  description: "Generated by Asmath Hussain S",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="shadow-[0px_0px_3px_0px_rgba(0,0,0,0.25)] p-4 mb-4">
          <Header />
        </div>

        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
